# deadlyworld:worldgen/minecraft/the_nether/environmental_hazards.toml
# This config contains options for misc environmental hazard features specific to the 'the_nether' dimension from
#   'minecraft'.


# Category: buried_blocks
# Settings related to buried blocks in the world; single-block 'ore veins' of varying kinds that generate in the
#   ground, not exposed to air.

  # Registry entry-value list fields: General format = [ "namespace:registry_name value1 value2 ...", ... ]
  #   Registry entry-value lists are arrays of registry keys. Many things in the game, such as blocks or potions, are
  #     defined by their registry key within a registry. For example, all items are registered in the "minecraft:item"
  #     registry.
  #   Registry entry-value lists may have one or multiple numeric values linked to each entry.
  #   'default' can be used instead of a registry key to provide default values.
  #   An asterisk '*' can be used to match all registry entries/keys belonging to X namespace. For example,
  #     'minecraft:*' will match all vanilla entries.
  #   Tags can also be used here. To declare a tag, start with a '#' followed by the rest of the tag path.
  #   Tag example: '#minecraft:oak_logs'
  #       Priority order: specific entries > tag entries > namespace entries > default

  # This list defines buried block entries. Each entry consists of the following in the given order:
  # Block ID - for example "minecraft:water" or "minecraft:cactus".
  # Min height - the lowest Y coordinate this block can generate at.
  # Max height - the highest Y coordinate this block can generate at.
  # Placements - the amount of times the world generator will try to place this block in a chunk.
  # Overriding this setting via data pack is NOT supported.
  # <Registry Entry-value List> Format: [ "namespace:registry_name value1 value2 value3", ... ], Default: [
  #   "minecraft:chest 1.0 120.0 5.0", "deadlyworld:inactive_buried_deadly_spawner 1.0 120.0 10.0", "minecraft:lava 1.0
  #   120.0 10.0" ]
  #    Target registry: ResourceKey[minecraft:root / minecraft:block]
  #    Range for Values: Any Value
  buried_blocks.list = [
    "minecraft:chest 1.0 120.0 5.0",
    "deadlyworld:inactive_buried_deadly_spawner 1.0 120.0 10.0",
    "minecraft:lava 1.0 120.0 10.0"
  ]

  # The loot table to apply to any 'buried' chest blocks generated in this dimension.
  # Overriding this setting via data pack is NOT supported.
  # <String> Default: "deadlyworld:chests/the_nether_buried"
  buried_blocks.chest_loot_table = "deadlyworld:chests/the_nether_buried"
